services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kb
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    ports: ["11435:11434"]
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      # NVIDIA GPU Support
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      # AMD GPU Support (uncomment if using AMD)
      # - HSA_OVERRIDE_GFX_VERSION=10.3.0
      # - HIP_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            # For NVIDIA GPUs
            - driver: nvidia
              count: all
              capabilities: [gpu]
            # For AMD GPUs (uncomment if using AMD)
            # - driver: rocm
            #   count: all
            #   capabilities: [gpu]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    build: ./apps/api
    ports: ["4000:4000"]
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/kb"
      REDIS_URL: "redis://redis:6379"
      LLM_PROVIDER: "ollama"
      OLLAMA_BASE_URL: "http://ollama:11434"
      PORT: 4000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./vault:/app/vault

  worker:
    build: ./apps/worker
    environment:
      REDIS_URL: "redis://redis:6379"
      API_URL: "http://api:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started

  web:
    build: ./apps/web
    ports: ["5173:80"]
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
  ollama_data:
